### ISSUE TITLE
ReadStream - Error: "start" option must be <= "end" option

### ISSUE THREAD

**Issue by sylwesterdigital** [daspinola/video-stream-sample#7]
Hello,
Thanks for publishing your idea of nodejs video streaming.  I have just tried to play short video from my iPhone and have this message:

```
Error: "start" option must be <= "end" option
    at new ReadStream (fs.js:1971:13)
```

Any idea how to fix that? 

Full output from the server
```
Listening on port 3000!
Error: "start" option must be <= "end" option
    at new ReadStream (fs.js:1971:13)
    at Object.fs.createReadStream (fs.js:1931:10)
    at /home/sylwester/apis/stream/server.js:26:21
    at Layer.handle [as handle_request] (/home/sylwester/apis/stream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sylwester/apis/stream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sylwester/apis/stream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sylwester/apis/stream/node_modules/express/lib/router/layer.js:95:5)
    at /home/sylwester/apis/stream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/sylwester/apis/stream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sylwester/apis/stream/node_modules/express/lib/router/index.js:275:10)
Error: "start" option must be <= "end" option
    at new ReadStream (fs.js:1971:13)
    at Object.fs.createReadStream (fs.js:1931:10)
    at /home/sylwester/apis/stream/server.js:26:21
    at Layer.handle [as handle_request] (/home/sylwester/apis/stream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sylwester/apis/stream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sylwester/apis/stream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sylwester/apis/stream/node_modules/express/lib/router/layer.js:95:5)
    at /home/sylwester/apis/stream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/sylwester/apis/stream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sylwester/apis/stream/node_modules/express/lib/router/index.js:275:10)
```

**Comment by daspinola** [comment]
Did you find out how to fix it?

The error happens when the `start` is bigger than `end` on this [line](https://github.com/daspinola/video-stream-sample/blob/master/server.js#L26)

**Comment by duzun** [comment]
According to [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.16), the response code should be 416:

> A server sending a response with status code 416 (Requested range not satisfiable) SHOULD include a Content-Range field with a byte-range- resp-spec of "*". The instance-length specifies the current length of the selected resource.

```js
if(start >= fileSize) {
  res.status(416).send('Requested range not satisfiable\n'+start+' >= '+fileSize);
  return;
}
```
